# This playbook prints a simple debug message
- name: My first Playbook
  hosts: initial
  tasks:
    - name: Ping my host
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
